# Generated by Django 5.2.8 on 2026-02-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'DRAFT'), ('Published', 'PUBLISHED')], default='Draft'),
        ),
    ]
