# Generated by Django 5.2.8 on 2026-02-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_socials_alter_about_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socials',
            new_name='Social',
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name_plural': 'Socials'},
        ),
    ]
